# Generated by Django 2.2.24 on 2022-04-21 12:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0200_auto_20220420_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='acceptance_criteria',
            field=models.TextField(blank=True, default='', help_text='Acceptance criteria', null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='bounty_source',
            field=models.CharField(choices=[('github', 'Github'), ('custom', 'Custom')], db_index=True, default='github', max_length=50),
        ),
        migrations.AddField(
            model_name='bounty',
            name='contact_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='peg_to_usd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bounty',
            name='resources',
            field=models.TextField(blank=True, default='', help_text='Resources', null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='usd_pegged_value_in_token',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='usd_pegged_value_in_token_now',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='value_true_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='bounty_type',
            field=models.CharField(blank=True, choices=[('Bug', 'Bug'), ('Project', 'Project'), ('Feature', 'Feature'), ('Security', 'Security'), ('Improvement', 'Improvement'), ('Design', 'Design'), ('Docs', 'Docs'), ('Code review', 'Code review'), ('Other', 'Other'), ('Unknown', 'Unknown')], db_index=True, max_length=50),
        ),
    ]
