# Generated by Django 2.2.24 on 2022-04-24 09:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0201_auto_20220421_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='owners',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
