# Generated by Django 2.2.24 on 2022-04-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0202_bounty_owners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bounty',
            name='owners',
        ),
    ]
