# Generated by Django 2.2.24 on 2022-04-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0203_remove_bounty_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='owners',
            field=models.ManyToManyField(to='dashboard.Profile'),
        ),
    ]
