# Generated by Django 2.2.24 on 2022-04-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0204_bounty_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='payout_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
