# Generated by Django 2.2.24 on 2022-04-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0205_auto_20220328_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bounty',
            name='tags',
        ),
        migrations.AlterField(
            model_name='bounty',
            name='bounty_type',
            field=models.CharField(blank=True, choices=[('Bug', 'Bug'), ('Project', 'Project'), ('Feature', 'Feature'), ('Security', 'Security'), ('Improvement', 'Improvement'), ('Design', 'Design'), ('Docs', 'Docs'), ('Code review', 'Code review'), ('Other', 'Other'), ('Unknown', 'Unknown')], db_index=True, max_length=50),
        ),
    ]
