# Generated by Django 2.2.24 on 2022-04-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0205_bounty_payout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='github_url',
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='owners',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.Profile'),
        ),
    ]
