# Generated by Django 2.2.24 on 2022-04-08 13:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0206_auto_20220408_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
    ]
