# Generated by Django 2.2.24 on 2022-04-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0207_bounty_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bounty',
            name='tags',
        ),
    ]
