# Generated by Django 2.2.24 on 2022-04-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0210_auto_20220420_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bounty',
            old_name='value_in_token_now',
            new_name='usd_pegged_value_in_token_now',
        ),
        migrations.AddField(
            model_name='bounty',
            name='usd_pegged_value_in_token',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='value_in_token',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=50),
        ),
    ]
